name: LIBFT CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-venv

    - name: make
      run: make

    - name: Check Norminette
      run: bash ./.github/norme_check.sh
      working-directory: ${{ github.workspace }}

    - name: make fclean
      run: make fclean
